<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:gml="http://www.opengis.net/gml" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>Road-LOD0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>-6.0 -6.0 0.0</gml:lowerCorner>
      <gml:upperCorner>245.0 225.0 25.0</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <tran:Road gml:id="36c4d995-ab7f-4270-a4c9-76561bd3c531">
      <tran:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="f4a8105d-2424-45af-9a13-ba97fcca2774">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>-6.0 -6.0 0.0 245.0 -6.0 0.0 245.0 225.0 0.0 -6.0 225.0 0.0 -6.0 -6.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 -1.0 0.0 -1.0 34.0 0.0 34.0 34.0 0.0 34.0 -1.0 0.0 -1.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 39.0 0.0 -1.0 74.0 0.0 34.0 74.0 0.0 34.0 39.0 0.0 -1.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 79.0 0.0 -1.0 114.0 0.0 34.0 114.0 0.0 34.0 79.0 0.0 -1.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 119.0 0.0 -1.0 154.0 0.0 34.0 154.0 0.0 34.0 119.0 0.0 -1.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 159.0 0.0 -1.0 194.0 0.0 34.0 194.0 0.0 34.0 159.0 0.0 -1.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 199.0 0.0 -1.0 220.0 0.0 34.0 220.0 0.0 34.0 199.0 0.0 -1.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 -1.0 0.0 39.0 34.0 0.0 74.0 34.0 0.0 74.0 -1.0 0.0 39.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 39.0 0.0 39.0 74.0 0.0 74.0 74.0 0.0 74.0 39.0 0.0 39.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 79.0 0.0 39.0 114.0 0.0 74.0 114.0 0.0 74.0 79.0 0.0 39.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 119.0 0.0 39.0 154.0 0.0 74.0 154.0 0.0 74.0 119.0 0.0 39.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 159.0 0.0 39.0 194.0 0.0 74.0 194.0 0.0 74.0 159.0 0.0 39.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>39.0 199.0 0.0 39.0 220.0 0.0 74.0 220.0 0.0 74.0 199.0 0.0 39.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 -1.0 0.0 79.0 34.0 0.0 114.0 34.0 0.0 114.0 -1.0 0.0 79.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 39.0 0.0 79.0 74.0 0.0 114.0 74.0 0.0 114.0 39.0 0.0 79.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 79.0 0.0 79.0 114.0 0.0 114.0 114.0 0.0 114.0 79.0 0.0 79.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 119.0 0.0 79.0 154.0 0.0 114.0 154.0 0.0 114.0 119.0 0.0 79.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 159.0 0.0 79.0 194.0 0.0 114.0 194.0 0.0 114.0 159.0 0.0 79.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>79.0 199.0 0.0 79.0 220.0 0.0 114.0 220.0 0.0 114.0 199.0 0.0 79.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 -1.0 0.0 119.0 34.0 0.0 154.0 34.0 0.0 154.0 -1.0 0.0 119.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 39.0 0.0 119.0 74.0 0.0 154.0 74.0 0.0 154.0 39.0 0.0 119.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 79.0 0.0 119.0 114.0 0.0 154.0 114.0 0.0 154.0 79.0 0.0 119.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 119.0 0.0 119.0 154.0 0.0 154.0 154.0 0.0 154.0 119.0 0.0 119.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 159.0 0.0 119.0 194.0 0.0 154.0 194.0 0.0 154.0 159.0 0.0 119.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 199.0 0.0 119.0 220.0 0.0 154.0 220.0 0.0 154.0 199.0 0.0 119.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 -1.0 0.0 159.0 34.0 0.0 194.0 34.0 0.0 194.0 -1.0 0.0 159.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 39.0 0.0 159.0 74.0 0.0 194.0 74.0 0.0 194.0 39.0 0.0 159.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 79.0 0.0 159.0 114.0 0.0 194.0 114.0 0.0 194.0 79.0 0.0 159.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 119.0 0.0 159.0 154.0 0.0 194.0 154.0 0.0 194.0 119.0 0.0 159.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 159.0 0.0 159.0 194.0 0.0 194.0 194.0 0.0 194.0 159.0 0.0 159.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>159.0 199.0 0.0 159.0 220.0 0.0 194.0 220.0 0.0 194.0 199.0 0.0 159.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 -1.0 0.0 199.0 34.0 0.0 240.0 34.0 0.0 240.0 -1.0 0.0 199.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 39.0 0.0 199.0 74.0 0.0 240.0 74.0 0.0 240.0 39.0 0.0 199.0 39.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 79.0 0.0 199.0 114.0 0.0 240.0 114.0 0.0 240.0 79.0 0.0 199.0 79.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 119.0 0.0 199.0 154.0 0.0 240.0 154.0 0.0 240.0 119.0 0.0 199.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 159.0 0.0 199.0 194.0 0.0 240.0 194.0 0.0 240.0 159.0 0.0 199.0 159.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>199.0 199.0 0.0 199.0 220.0 0.0 240.0 220.0 0.0 240.0 199.0 0.0 199.0 199.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </tran:lod1MultiSurface>
    </tran:Road>
  </cityObjectMember>
</CityModel>
