<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Random3Dcity (http://github.com/tudelft3d/Random3Dcity), a tool developed by Filip Biljecki at TU Delft. Version: 2015-03-11. -->
<CityModel xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:gml="http://www.opengis.net/gml" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/citygml/2.0">
  <gml:name>Road-LOD0</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:28992">
      <gml:lowerCorner>-6.0 -6.0 0.0</gml:lowerCorner>
      <gml:upperCorner>165.0 145.0 25.0</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <tran:Road gml:id="b5683493-73e2-41dc-b83c-874853ed21bb">
      <tran:lod1MultiSurface>
        <gml:MultiSurface>
          <gml:surfaceMember>
            <gml:Polygon gml:id="707e48bc-527e-4eec-9231-f8b3fe4a8d55">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>-6.0 -6.0 0.0 165.0 -6.0 0.0 165.0 145.0 0.0 -6.0 145.0 0.0 -6.0 -6.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 -1.0 0.0 -1.0 54.0 0.0 54.0 54.0 0.0 54.0 -1.0 0.0 -1.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 59.0 0.0 -1.0 114.0 0.0 54.0 114.0 0.0 54.0 59.0 0.0 -1.0 59.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>-1.0 119.0 0.0 -1.0 140.0 0.0 54.0 140.0 0.0 54.0 119.0 0.0 -1.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>59.0 -1.0 0.0 59.0 54.0 0.0 114.0 54.0 0.0 114.0 -1.0 0.0 59.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>59.0 59.0 0.0 59.0 114.0 0.0 114.0 114.0 0.0 114.0 59.0 0.0 59.0 59.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>59.0 119.0 0.0 59.0 140.0 0.0 114.0 140.0 0.0 114.0 119.0 0.0 59.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 -1.0 0.0 119.0 54.0 0.0 160.0 54.0 0.0 160.0 -1.0 0.0 119.0 -1.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 59.0 0.0 119.0 114.0 0.0 160.0 114.0 0.0 160.0 59.0 0.0 119.0 59.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
              <gml:interior>
                <gml:LinearRing>
                  <gml:posList>119.0 119.0 0.0 119.0 140.0 0.0 160.0 140.0 0.0 160.0 119.0 0.0 119.0 119.0 0.0</gml:posList>
                </gml:LinearRing>
              </gml:interior>
            </gml:Polygon>
          </gml:surfaceMember>
        </gml:MultiSurface>
      </tran:lod1MultiSurface>
    </tran:Road>
  </cityObjectMember>
</CityModel>
